

export const ActionTypes = Object.freeze({

    PRODUCT_LIST_REQUEST    : 'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_UPDATE     : 'PRODUCT_LIST_UPDATE',
    PRODUCT_SELECT          : 'PRODUCT_SELECT',

    NETWORK_STATUS_ON       : 'NETWORK_STATUS_ON',
    NETWORK_STATUS_OFF      : 'NETWORK_STATUS_OFF',

    NETWORK_ACTIVITY_IDLE   : 'NETWORK_ACTIVITY_IDLE',
    NETWORK_ACTIVITY_BUSY   : 'NETWORK_ACTIVITY_BUSY',

})